In [1]:
import torch

In [2]:
c1 = torch.nn.Sequential(
    torch.nn.Linear(2,3),
    torch.nn.Linear(3,2)
)

In [6]:
c1[0].weight

Parameter containing:
tensor([[0.2598, 0.1572],
        [0.0313, 0.0027],
        [0.1988, 0.3007]], requires_grad=True)

In [7]:
c1.to("cuda")

Sequential(
  (0): Linear(in_features=2, out_features=3, bias=True)
  (1): Linear(in_features=3, out_features=2, bias=True)
)

In [3]:
c2 = torch.nn.Sequential(
    torch.nn.Linear(2,3),
    torch.nn.Linear(3,2)
)

In [5]:
c2[0].weight

Parameter containing:
tensor([[-0.2052,  0.4235],
        [ 0.0068, -0.3945],
        [ 0.0927, -0.2039]], requires_grad=True)

In [8]:
c2.load_state_dict(c1.state_dict())
c2[0].weight

Parameter containing:
tensor([[0.2598, 0.1572],
        [0.0313, 0.0027],
        [0.1988, 0.3007]], requires_grad=True)

In [9]:
c1.to("cpu")

Sequential(
  (0): Linear(in_features=2, out_features=3, bias=True)
  (1): Linear(in_features=3, out_features=2, bias=True)
)

In [1]:
from datasets import load_dataset
sst2_dataset = load_dataset("sst2")
imdb_dataset = load_dataset("imdb")

In [2]:
sst2_dataset

DatasetDict({
    train: Dataset({
        features: ['idx', 'sentence', 'label'],
        num_rows: 67349
    })
    validation: Dataset({
        features: ['idx', 'sentence', 'label'],
        num_rows: 872
    })
    test: Dataset({
        features: ['idx', 'sentence', 'label'],
        num_rows: 1821
    })
})

In [3]:
imdb_dataset

DatasetDict({
    train: Dataset({
        features: ['text', 'label'],
        num_rows: 25000
    })
    test: Dataset({
        features: ['text', 'label'],
        num_rows: 25000
    })
    unsupervised: Dataset({
        features: ['text', 'label'],
        num_rows: 50000
    })
})